spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    name: postgres
    password: postgres
  liquibase:
    change-log: db/changelog/db.changelog.xml
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 3000
env:
  url: